import { useState } from 'react';
import { Card, Button, TextArea, Input, Select } from '../components/common';

type ProjectType = 'node' | 'react' | 'vue' | 'nextjs' | 'python' | 'go' | 'java' | 'nginx';

interface DockerConfig {
  name: string;
  description: string;
  template: (config: ConfigState) => string;
}

interface ConfigState {
  port: string;
  appName: string;
  nodeVersion: string;
  pythonVersion: string;
  goVersion: string;
  workDir: string;
  buildCommand: string;
  startCommand: string;
  envVars: string;
}

const dockerTemplates: Record<ProjectType, DockerConfig> = {
  node: {
    name: 'Node.js',
    description: 'Node.js 应用 Dockerfile',
    template: (config) => `# Node.js Application Dockerfile
# Generated by DevTools

FROM node:${config.nodeVersion}-alpine

WORKDIR /${config.workDir}

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy source code
COPY . .

# Build application (if needed)
${config.buildCommand ? `RUN ${config.buildCommand}` : '# No build command specified'}

# Expose port
EXPOSE ${config.port}

# Environment variables
${config.envVars ? config.envVars.split('\n').map(e => `ENV ${e}`).join('\n') : '# No custom environment variables'}

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD node healthcheck.js || exit 1

# Start application
CMD ["node", "${config.startCommand || 'index.js'}"]
`,
  },
  react: {
    name: 'React',
    description: 'React 应用 Dockerfile (多阶段构建)',
    template: (config) => `# React Application Dockerfile
# Multi-stage build for optimized production image
# Generated by DevTools

# Stage 1: Build
FROM node:${config.nodeVersion}-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install all dependencies (including devDependencies)
RUN npm ci

# Copy source code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Production
FROM nginx:alpine

# Copy custom nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# Copy built files from builder stage
COPY --from=builder /app/build /usr/share/nginx/html

# Expose port
EXPOSE ${config.port}

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
`,
  },
  vue: {
    name: 'Vue.js',
    description: 'Vue.js 应用 Dockerfile (多阶段构建)',
    template: (config) => `# Vue.js Application Dockerfile
# Multi-stage build for optimized production image
# Generated by DevTools

# Stage 1: Build
FROM node:${config.nodeVersion}-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Production
FROM nginx:alpine

# Copy nginx configuration
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/

# Copy built files from builder stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port
EXPOSE ${config.port}

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
`,
  },
  nextjs: {
    name: 'Next.js',
    description: 'Next.js 应用 Dockerfile (独立输出模式)',
    template: (config) => `# Next.js Application Dockerfile
# Requires output: 'standalone' in next.config.js
# Generated by DevTools

FROM node:${config.nodeVersion}-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data
ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE ${config.port}

ENV PORT ${config.port}
ENV HOSTNAME "0.0.0.0"

CMD ["node", "server.js"]
`,
  },
  python: {
    name: 'Python',
    description: 'Python 应用 Dockerfile',
    template: (config) => `# Python Application Dockerfile
# Generated by DevTools

FROM python:${config.pythonVersion}-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /${config.workDir}

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    gcc \\
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Expose port
EXPOSE ${config.port}

# Environment variables
${config.envVars ? config.envVars.split('\n').map(e => `ENV ${e}`).join('\n') : '# No custom environment variables'}

# Start application
CMD ["python", "${config.startCommand || 'app.py'}"]
`,
  },
  go: {
    name: 'Go',
    description: 'Go 应用 Dockerfile (多阶段构建)',
    template: (config) => `# Go Application Dockerfile
# Multi-stage build for minimal production image
# Generated by DevTools

# Stage 1: Build
FROM golang:${config.goVersion}-alpine AS builder

WORKDIR /app

# Install git (required for go mod download)
RUN apk add --no-cache git

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the binary
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# Stage 2: Production
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy binary from builder
COPY --from=builder /app/main .

# Expose port
EXPOSE ${config.port}

# Environment variables
${config.envVars ? config.envVars.split('\n').map(e => `ENV ${e}`).join('\n') : '# No custom environment variables'}

# Run the binary
CMD ["./main"]
`,
  },
  java: {
    name: 'Java',
    description: 'Java Spring Boot 应用 Dockerfile',
    template: (config) => `# Java Spring Boot Application Dockerfile
# Generated by DevTools

# Build stage
FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn package -DskipTests

# Run stage
FROM eclipse-temurin:17-jre-jammy

WORKDIR /app

# Create non-root user
RUN groupadd -r appuser && useradd -r -g appuser appuser

# Copy jar from build stage
COPY --from=build /app/target/*.jar app.jar

# Change ownership
RUN chown -R appuser:appuser /app
USER appuser

# Expose port
EXPOSE ${config.port}

# Environment variables
${config.envVars ? config.envVars.split('\n').map(e => `ENV ${e}`).join('\n') : '# No custom environment variables'}

# JVM options
ENV JAVA_OPTS="-Xms256m -Xmx512m"

# Start application
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
`,
  },
  nginx: {
    name: 'Nginx',
    description: 'Nginx 静态文件服务器',
    template: (config) => `# Nginx Static Server Dockerfile
# Generated by DevTools

FROM nginx:alpine

# Remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom nginx configuration
COPY nginx.conf /etc/nginx/conf.d/

# Copy static files
COPY dist/ /usr/share/nginx/html/

# Expose port
EXPOSE ${config.port}

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD wget --quiet --tries=1 --spider http://localhost:${config.port}/ || exit 1

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
`,
  },
};

const nginxConfigTemplate = `# Nginx configuration for SPA
server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;

    # Cache static assets
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
}
`;

export default function DockerfileGenerator() {
  const [projectType, setProjectType] = useState<ProjectType>('node');
  const [showNginxConfig, setShowNginxConfig] = useState(false);
  const [output, setOutput] = useState('');
  const [config, setConfig] = useState<ConfigState>({
    port: '3000',
    appName: 'myapp',
    nodeVersion: '20',
    pythonVersion: '3.11',
    goVersion: '1.21',
    workDir: 'app',
    buildCommand: '',
    startCommand: 'index.js',
    envVars: '',
  });

  const generateDockerfile = () => {
    const template = dockerTemplates[projectType];
    if (template) {
      setOutput(template.template(config));
    }
  };

  const copyOutput = () => {
    navigator.clipboard.writeText(output);
  };

  const downloadFile = () => {
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'Dockerfile';
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadNginxConfig = () => {
    const blob = new Blob([nginxConfigTemplate], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'nginx.conf';
    a.click();
    URL.revokeObjectURL(url);
  };

  const updateConfig = (key: keyof ConfigState, value: string) => {
    setConfig(prev => ({ ...prev, [key]: value }));
  };

  return (
    <div style={{ display: 'grid', gap: '20px' }}>
      <Card title="Dockerfile 生成器">
        <p style={{ color: 'var(--text-secondary)', marginBottom: '16px' }}>
          选择项目类型，自动生成优化的 Dockerfile
        </p>

        <div style={{ marginBottom: '20px' }}>
          <div style={{ fontWeight: 600, marginBottom: '12px' }}>项目类型</div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(120px, 1fr))', gap: '8px' }}>
            {Object.entries(dockerTemplates).map(([key, value]) => (
              <button
                key={key}
                onClick={() => setProjectType(key as ProjectType)}
                style={{
                  padding: '12px',
                  border: 'none',
                  borderRadius: '8px',
                  cursor: 'pointer',
                  fontSize: '14px',
                  background: projectType === key
                    ? 'var(--accent-primary)'
                    : 'var(--bg-secondary)',
                  color: projectType === key
                    ? 'white'
                    : 'var(--text-primary)',
                  textAlign: 'left',
                }}
              >
                <div style={{ fontWeight: 600 }}>{value.name}</div>
              </button>
            ))}
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '16px', marginBottom: '20px' }}>
          <Input
            label="端口"
            value={config.port}
            onChange={e => updateConfig('port', e.target.value)}
            placeholder="3000"
          />
          <Input
            label="工作目录"
            value={config.workDir}
            onChange={e => updateConfig('workDir', e.target.value)}
            placeholder="app"
          />
        </div>

        {(projectType === 'node' || projectType === 'react' || projectType === 'vue' || projectType === 'nextjs') && (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '16px', marginBottom: '20px' }}>
            <Select
              label="Node 版本"
              value={config.nodeVersion}
              onChange={e => updateConfig('nodeVersion', e.target.value)}
              options={[
                { value: '22', label: 'Node 22 (Latest)' },
                { value: '20', label: 'Node 20 (LTS)' },
                { value: '18', label: 'Node 18 (LTS)' },
                { value: '16', label: 'Node 16' },
              ]}
            />
            <Input
              label="启动文件"
              value={config.startCommand}
              onChange={e => updateConfig('startCommand', e.target.value)}
              placeholder="index.js"
            />
          </div>
        )}

        {projectType === 'python' && (
          <div style={{ marginBottom: '20px' }}>
            <Select
              label="Python 版本"
              value={config.pythonVersion}
              onChange={e => updateConfig('pythonVersion', e.target.value)}
              options={[
                { value: '3.12', label: 'Python 3.12 (Latest)' },
                { value: '3.11', label: 'Python 3.11' },
                { value: '3.10', label: 'Python 3.10' },
                { value: '3.9', label: 'Python 3.9' },
              ]}
            />
          </div>
        )}

        {projectType === 'go' && (
          <div style={{ marginBottom: '20px' }}>
            <Select
              label="Go 版本"
              value={config.goVersion}
              onChange={e => updateConfig('goVersion', e.target.value)}
              options={[
                { value: '1.22', label: 'Go 1.22 (Latest)' },
                { value: '1.21', label: 'Go 1.21' },
                { value: '1.20', label: 'Go 1.20' },
              ]}
            />
          </div>
        )}

        <div style={{ marginBottom: '20px' }}>
          <Input
            label="构建命令 (可选)"
            value={config.buildCommand}
            onChange={e => updateConfig('buildCommand', e.target.value)}
            placeholder="npm run build"
          />
        </div>

        <div style={{ marginBottom: '20px' }}>
          <div style={{ fontWeight: 600, marginBottom: '8px' }}>环境变量 (每行一个，格式: KEY=value)</div>
          <TextArea
            value={config.envVars}
            onChange={e => updateConfig('envVars', e.target.value)}
            placeholder="NODE_ENV=production&#10;API_URL=https://api.example.com"
            style={{ minHeight: '80px' }}
          />
        </div>

        <div style={{ display: 'flex', gap: '12px' }}>
          <Button variant="primary" onClick={generateDockerfile}>生成 Dockerfile</Button>
          {(projectType === 'react' || projectType === 'vue' || projectType === 'nginx') && (
            <Button variant="secondary" onClick={() => setShowNginxConfig(!showNginxConfig)}>
              查看 Nginx 配置
            </Button>
          )}
        </div>
      </Card>

      {output && (
        <Card title="Dockerfile">
          <div style={{ display: 'flex', gap: '8px', marginBottom: '12px' }}>
            <Button variant="secondary" size="sm" onClick={copyOutput}>复制</Button>
            <Button variant="primary" size="sm" onClick={downloadFile}>下载 Dockerfile</Button>
          </div>
          <pre className="result-box" style={{ margin: 0, maxHeight: '500px', overflow: 'auto' }}>
            {output}
          </pre>
        </Card>
      )}

      {showNginxConfig && (
        <Card title="nginx.conf (可选)">
          <div style={{ display: 'flex', gap: '8px', marginBottom: '12px' }}>
            <Button variant="secondary" size="sm" onClick={() => navigator.clipboard.writeText(nginxConfigTemplate)}>复制</Button>
            <Button variant="secondary" size="sm" onClick={downloadNginxConfig}>下载 nginx.conf</Button>
          </div>
          <pre className="result-box" style={{ margin: 0, maxHeight: '300px', overflow: 'auto' }}>
            {nginxConfigTemplate}
          </pre>
        </Card>
      )}
    </div>
  );
}